"use client";

import { useMemo } from "react";
import Link from "next/link";
import { motion } from "framer-motion";
import {
  Shield,
  AlertTriangle,
  AlertCircle,
  Info,
  ArrowRight,
  FileJson,
} from "lucide-react";
import { useArtifactStore } from "@/lib/store";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import { UploadDropzone } from "@/components/UploadDropzone";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { RiskPosture } from "@/components/RiskPosture";

export default function DashboardPage() {
  const { artifacts, selectedArtifactId } = useArtifactStore();
  const selectedArtifact = useMemo(
    () => artifacts.find((a) => a.id === selectedArtifactId),
    [artifacts, selectedArtifactId]
  );

  const findings = selectedArtifact?.artifact.findings ?? [];

  const severityCounts = useMemo(() => {
    const counts = { critical: 0, high: 0, medium: 0, low: 0, info: 0 };
    findings.forEach((f) => {
      const sev = f.severity.toLowerCase() as keyof typeof counts;
      if (sev in counts) counts[sev]++;
    });
    return counts;
  }, [findings]);

  return (
    <div className="min-h-screen flex flex-col bg-background">
      <Header />

      <main className="flex-1 container py-8">
        <div className="space-y-8">
          {/* Page Header */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.3 }}
          >
            <h1 className="text-3xl font-bold tracking-tight">Dashboard</h1>
            <p className="text-muted-foreground mt-1">
              Import and analyze security scan artifacts
            </p>
          </motion.div>

          {/* Upload Section */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.3, delay: 0.1 }}
          >
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <FileJson className="w-5 h-5" />
                  Import Artifact
                </CardTitle>
              </CardHeader>
              <CardContent>
                <UploadDropzone />
                <p className="text-xs text-muted-foreground mt-3">
                  Import a <code className="px-1 py-0.5 bg-muted rounded">vibecheck-scan.json</code> file generated by the CLI
                </p>
              </CardContent>
            </Card>
          </motion.div>

          {/* Summary Section - Only show when artifact is loaded */}
          {selectedArtifact && (
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.3, delay: 0.2 }}
              className="space-y-6"
            >
              {/* Artifact Info */}
              <Card>
                <CardHeader className="pb-3">
                  <div className="flex items-center justify-between">
                    <CardTitle>Current Scan</CardTitle>
                    <Link href="/findings">
                      <Button size="sm" className="gap-2">
                        View Findings
                        <ArrowRight className="w-4 h-4" />
                      </Button>
                    </Link>
                  </div>
                </CardHeader>
                <CardContent>
                  <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
                    <div className="space-y-1">
                      <p className="text-sm text-muted-foreground">Repository</p>
                      <p className="font-medium">
                        {selectedArtifact.artifact.repo?.name ?? "Unknown"}
                      </p>
                    </div>
                    <div className="space-y-1">
                      <p className="text-sm text-muted-foreground">Scanned</p>
                      <p className="font-medium">
                        {new Date(selectedArtifact.artifact.generatedAt).toLocaleDateString()}
                      </p>
                    </div>
                    <div className="space-y-1">
                      <p className="text-sm text-muted-foreground">Scanner Version</p>
                      <p className="font-medium">{selectedArtifact.artifact.tool?.version ?? "-"}</p>
                    </div>
                    <div className="space-y-1">
                      <p className="text-sm text-muted-foreground">Total Findings</p>
                      <p className="font-medium">{findings.length}</p>
                    </div>
                  </div>
                </CardContent>
              </Card>

              {/* Severity Breakdown */}
              <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-5">
                <SeverityCard
                  label="Critical"
                  count={severityCounts.critical}
                  icon={AlertCircle}
                  color="text-red-500"
                  bgColor="bg-red-500/10"
                />
                <SeverityCard
                  label="High"
                  count={severityCounts.high}
                  icon={AlertTriangle}
                  color="text-orange-500"
                  bgColor="bg-orange-500/10"
                />
                <SeverityCard
                  label="Medium"
                  count={severityCounts.medium}
                  icon={AlertTriangle}
                  color="text-yellow-500"
                  bgColor="bg-yellow-500/10"
                />
                <SeverityCard
                  label="Low"
                  count={severityCounts.low}
                  icon={Info}
                  color="text-blue-500"
                  bgColor="bg-blue-500/10"
                />
                <SeverityCard
                  label="Info"
                  count={severityCounts.info}
                  icon={Info}
                  color="text-slate-500"
                  bgColor="bg-slate-500/10"
                />
              </div>

              {/* Risk Posture */}
              <RiskPosture severityCounts={severityCounts} />
            </motion.div>
          )}

          {/* Empty state when no artifact */}
          {!selectedArtifact && artifacts.length === 0 && (
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.3, delay: 0.2 }}
            >
              <Card>
                <CardContent className="py-12 text-center">
                  <Shield className="w-12 h-12 text-muted-foreground mx-auto mb-4" />
                  <h3 className="text-lg font-semibold mb-2">No artifacts imported</h3>
                  <p className="text-muted-foreground max-w-md mx-auto">
                    Run <code className="px-1.5 py-0.5 bg-muted rounded text-sm">vibecheck scan</code> in your project directory, then import the generated artifact to view security findings.
                  </p>
                </CardContent>
              </Card>
            </motion.div>
          )}
        </div>
      </main>

      <Footer />
    </div>
  );
}

function SeverityCard({
  label,
  count,
  icon: Icon,
  color,
  bgColor,
}: {
  label: string;
  count: number;
  icon: typeof AlertCircle;
  color: string;
  bgColor: string;
}) {
  return (
    <Card>
      <CardContent className="pt-6">
        <div className="flex items-center justify-between">
          <div>
            <p className="text-sm text-muted-foreground">{label}</p>
            <p className={`text-2xl font-bold ${color}`}>{count}</p>
          </div>
          <div className={`p-3 rounded-full ${bgColor}`}>
            <Icon className={`w-5 h-5 ${color}`} />
          </div>
        </div>
      </CardContent>
    </Card>
  );
}
