"use client";

import { useState, useCallback } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Copy, Check } from "lucide-react";
import { Button } from "@/components/ui/button";
import type { ScanArtifact } from "@vibecheck/schema";

interface CopyReportProps {
  artifact: ScanArtifact;
  maxFindings?: number;
}

function generateMarkdownReport(artifact: ScanArtifact, maxFindings: number): string {
  const { summary, findings, repo, generatedAt, tool } = artifact;

  const topFindings = [...findings]
    .sort((a, b) => {
      const severityOrder = { critical: 4, high: 3, medium: 2, low: 1, info: 0 };
      const sevDiff = severityOrder[b.severity] - severityOrder[a.severity];
      if (sevDiff !== 0) return sevDiff;
      return b.confidence - a.confidence;
    })
    .slice(0, maxFindings);

  const lines: string[] = [
    `# VibeCheck Security Report`,
    ``,
    `**Repository:** ${repo?.name || "Unknown"}`,
    `**Scanned:** ${new Date(generatedAt).toLocaleString()}`,
    `**Tool:** ${tool.name} v${tool.version}`,
    ``,
    `## Summary`,
    ``,
    `| Severity | Count |`,
    `|----------|-------|`,
    `| Critical | ${summary.bySeverity.critical} |`,
    `| High | ${summary.bySeverity.high} |`,
    `| Medium | ${summary.bySeverity.medium} |`,
    `| Low | ${summary.bySeverity.low} |`,
    `| Info | ${summary.bySeverity.info} |`,
    `| **Total** | **${summary.totalFindings}** |`,
    ``,
  ];

  if (topFindings.length > 0) {
    lines.push(
      `## Top ${Math.min(maxFindings, topFindings.length)} Findings`,
      ``
    );

    topFindings.forEach((finding, index) => {
      lines.push(
        `### ${index + 1}. [${finding.severity.toUpperCase()}] ${finding.title}`,
        ``,
        `- **Rule:** \`${finding.ruleId}\``,
        `- **Category:** ${finding.category}`,
        `- **Confidence:** ${Math.round(finding.confidence * 100)}%`,
        ``,
        finding.description,
        ``
      );

      if (finding.evidence.length > 0) {
        const ev = finding.evidence[0];
        lines.push(
          `**Location:** \`${ev.file}:${ev.startLine}\``,
          ``
        );
        if (ev.snippet) {
          lines.push(
            "```",
            ev.snippet,
            "```",
            ``
          );
        }
      }

      lines.push(
        `**Remediation:** ${finding.remediation.recommendedFix}`,
        ``,
        `---`,
        ``
      );
    });
  }

  lines.push(
    `*Generated by VibeCheck*`
  );

  return lines.join("\n");
}

export function CopyReport({ artifact, maxFindings = 5 }: CopyReportProps) {
  const [copied, setCopied] = useState(false);

  const handleCopy = useCallback(async () => {
    const markdown = generateMarkdownReport(artifact, maxFindings);

    try {
      await navigator.clipboard.writeText(markdown);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error("Failed to copy:", err);
    }
  }, [artifact, maxFindings]);

  return (
    <Button
      variant="outline"
      size="sm"
      onClick={handleCopy}
      className="gap-2"
      aria-label={copied ? "Copied to clipboard" : "Copy report to clipboard"}
    >
      <AnimatePresence mode="wait" initial={false}>
        {copied ? (
          <motion.span
            key="check"
            initial={{ scale: 0 }}
            animate={{ scale: 1 }}
            exit={{ scale: 0 }}
            className="flex items-center gap-2"
          >
            <Check className="w-4 h-4 text-success" />
            Copied
          </motion.span>
        ) : (
          <motion.span
            key="copy"
            initial={{ scale: 0 }}
            animate={{ scale: 1 }}
            exit={{ scale: 0 }}
            className="flex items-center gap-2"
          >
            <Copy className="w-4 h-4" />
            Copy Report
          </motion.span>
        )}
      </AnimatePresence>
    </Button>
  );
}
